// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import 'frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// Status of the torrent download
class TorrentStatus {
  final BigInt totalPieces;
  final BigInt completedPieces;
  final BigInt peers;
  final double speedMbps;
  final BigInt downloadedBytes;

  const TorrentStatus({
    required this.totalPieces,
    required this.completedPieces,
    required this.peers,
    required this.speedMbps,
    required this.downloadedBytes,
  });

  @override
  int get hashCode =>
      totalPieces.hashCode ^
      completedPieces.hashCode ^
      peers.hashCode ^
      speedMbps.hashCode ^
      downloadedBytes.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is TorrentStatus &&
          runtimeType == other.runtimeType &&
          totalPieces == other.totalPieces &&
          completedPieces == other.completedPieces &&
          peers == other.peers &&
          speedMbps == other.speedMbps &&
          downloadedBytes == other.downloadedBytes;
}
