// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`, `clone`, `clone`, `clone`, `fmt`, `fmt`, `fmt`, `fmt`

Future<MagnetInfo> parseMagnet({required String uri}) =>
    RustLib.instance.api.crateApiSimpleParseMagnet(uri: uri);

Future<TorrentInfo> getTorrentInfoFile({required String path}) =>
    RustLib.instance.api.crateApiSimpleGetTorrentInfoFile(path: path);

Stream<AppTorrentStatus> startDownload(
        {required String source,
        required String outputDir,
        Uint64List? selectedFileIndices}) =>
    RustLib.instance.api.crateApiSimpleStartDownload(
        source: source,
        outputDir: outputDir,
        selectedFileIndices: selectedFileIndices);

Future<TorrentInfo> fetchMagnetMetadata(
        {required String magnetUri, required int timeoutSecs}) =>
    RustLib.instance.api.crateApiSimpleFetchMagnetMetadata(
        magnetUri: magnetUri, timeoutSecs: timeoutSecs);

class AppTorrentStatus {
  final int totalPieces;
  final int completedPieces;
  final int peers;
  final double speedMbps;
  final bool downloading;
  final bool isFetchingMetadata;
  final String statusMessage;
  final String? error;

  const AppTorrentStatus({
    required this.totalPieces,
    required this.completedPieces,
    required this.peers,
    required this.speedMbps,
    required this.downloading,
    required this.isFetchingMetadata,
    required this.statusMessage,
    this.error,
  });

  @override
  int get hashCode =>
      totalPieces.hashCode ^
      completedPieces.hashCode ^
      peers.hashCode ^
      speedMbps.hashCode ^
      downloading.hashCode ^
      isFetchingMetadata.hashCode ^
      statusMessage.hashCode ^
      error.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is AppTorrentStatus &&
          runtimeType == other.runtimeType &&
          totalPieces == other.totalPieces &&
          completedPieces == other.completedPieces &&
          peers == other.peers &&
          speedMbps == other.speedMbps &&
          downloading == other.downloading &&
          isFetchingMetadata == other.isFetchingMetadata &&
          statusMessage == other.statusMessage &&
          error == other.error;
}

class FileInfo {
  final String path;
  final BigInt size;

  const FileInfo({
    required this.path,
    required this.size,
  });

  @override
  int get hashCode => path.hashCode ^ size.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is FileInfo &&
          runtimeType == other.runtimeType &&
          path == other.path &&
          size == other.size;
}

class MagnetInfo {
  final String url;
  final String infoHash;
  final String? name;
  final List<String> trackers;

  const MagnetInfo({
    required this.url,
    required this.infoHash,
    this.name,
    required this.trackers,
  });

  @override
  int get hashCode =>
      url.hashCode ^ infoHash.hashCode ^ name.hashCode ^ trackers.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is MagnetInfo &&
          runtimeType == other.runtimeType &&
          url == other.url &&
          infoHash == other.infoHash &&
          name == other.name &&
          trackers == other.trackers;
}

class TorrentInfo {
  final String name;
  final BigInt totalSize;
  final BigInt pieceCount;
  final BigInt pieceLength;
  final List<FileInfo> files;
  final String infoHash;
  final String announce;

  const TorrentInfo({
    required this.name,
    required this.totalSize,
    required this.pieceCount,
    required this.pieceLength,
    required this.files,
    required this.infoHash,
    required this.announce,
  });

  @override
  int get hashCode =>
      name.hashCode ^
      totalSize.hashCode ^
      pieceCount.hashCode ^
      pieceLength.hashCode ^
      files.hashCode ^
      infoHash.hashCode ^
      announce.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is TorrentInfo &&
          runtimeType == other.runtimeType &&
          name == other.name &&
          totalSize == other.totalSize &&
          pieceCount == other.pieceCount &&
          pieceLength == other.pieceLength &&
          files == other.files &&
          infoHash == other.infoHash &&
          announce == other.announce;
}
